# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
