# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0003_redirection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('content_format', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze'), ('partner', 'partner')], max_length=255)),
                ('website', models.CharField(max_length=255, null=True)),
                ('twitter_handle', models.CharField(max_length=255, null=True)),
                ('logo_filename', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
