# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0004_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_sponsors',
            field=models.BooleanField(default=True),
        ),
    ]
