# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyconuk', '0006_auto_20171005_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='original_id',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
